### ISSUE TITLE
[ Week 7] 7주차 워크북 미션

### ISSUE THREAD

**Issue by hmj6589** [DS-UMC-7th/UMC-7th-Hazel#1]
### 🛠 Mission

워크북을 보며 API 응답 통일과 에러 핸들러 숙지

### 📝 To-do

- [ ] 워크북을 보며 API 응답 통일과 에러 핸들러 숙지
- [ ] 처음부터 끝까지 다 해보고 새 브랜치에 push
- [ ] RestControllerAdvice 장점, 없을 경우 어떤 점이 불편한지 조사
- [ ] 미션 목록 조회(진행 중, 진행 완료) API 명세서 작성

### 🔍 접근 방법

.
